version: '3.8'
services:
  ms-simulado:
    container_name: ms-simulado
    image: vcnafacul/simulado:latest
    env_file:
      - .env.qa
    restart: always
    networks:
      - vcnafacul-network

  api-vcnafacul:
    container_name: api-vcnafacul
    image: vcnafacul/api:latest
    ports:
      - 3333:3333
    env_file:
      - .env.qa
    restart: always
    depends_on:
      - ms-simulado
    networks:
      - vcnafacul-network
  
  web-vcnafacul:
    container_name: web-vcnafacul
    image: vcnafacul/web:latest
    ports:
      - 5173:80
    restart: always
    depends_on:
      - api-vcnafacul
    networks:
      - vcnafacul-network
  

networks:
  vcnafacul-network:
    driver: bridge