export const cursos = [
  "Acupuntura",
  "Administração",
  "Administração Pública",
  "Agrimensura",
  "Agronegócio",
  "Agrocomputação",
  "Agroecologia",
  "Agroindústria",
  "Agropecuária",
  "Agronomia",
  "Alimentos",
  "Análise e Desenvolvimento de Sistemas",
  "Antropologia",
  "Apicultura e Meliponicultura",
  "Aquicultura",
  "Arquitetura e Urbanismo",
  "Arquivologia",
  "Artes",
  "Artes Cênicas",
  "Artes do Espetáculo",
  "Artes e Mídias Digitais",
  "Artes Plásticas",
  "Artes Visuais",
  "Assessoramento Executivo Digital",
  "Astronomia",
  "Auditoria em Saúde",
  "Automação de Escritórios e Secretariado",
  "Biocombustíveis",
  "Biologia",
  "Biomedicina",
  "Bioenergia",
  "Bioinformática",
  "Bioquímica",
  "Biotecnologia",
  "Biblioteconomia",
  "Cafeicultura",
  "Canto",
  "Ciência da Computação",
  "Ciências Agrícolas",
  "Ciências Biológicas",
  "Ciências da Natureza",
  "Ciências Econômicas",
  "Ciências Sociais",
  "Cenografia",
  "Cinema e Audiovisual",
  "Coaching e Mentoring",
  "Coach Digital",
  "Comunicação Assistiva",
  "Comunicação Digital",
  "Comunicação e Marketing",
  "Comunicação em Mídias Digitais",
  "Comunicação Institucional",
  "Comunicação Social",
  "Comércio Exterior",
  "Composição e Regência",
  "Controle Ambiental",
  "Cosmetologia e Estética",
  "Cozinha Contemporânea",
  "Design",
  "Design Comercial",
  "Design de Ambientes",
  "Design de Aplicações e Interfaces Digitais",
  "Design de Animação",
  "Design de Experiência e de Serviços",
  "Design de Games",
  "Design de Interiores",
  "Design de Moda",
  "Design Digital",
  "Design de Produto",
  "Design Editorial",
  "Design Educacional",
  "Design Gráfico",
  "Desenho de Animação",
  "Desenho Industrial",
  "Direção",
  "Direito",
  "Economia",
  "E-Commerce",
  "Educação do Campo",
  "Educação e Processos de Trabalho: Alimentação Escolar",
  "Educador Social",
  "Embelezamento e Imagem Pessoal",
  "Engenharia Aeroespacial",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia de Alimentos",
  "Engenharia de Computação",
  "Engenharia de Controle e Automação",
  "Engenharia de Energia",
  "Engenharia de Produção",
  "Engenharia de Petróleo",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Engenharia Naval",
  "Engenharia Química",
  "Estética e Cosmética",
  "Estilismo",
  "Eventos",
  "Filmmaker",
  "Filosofia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Fotografia",
  "Fruticultura",
  "Futebol",
  "Gastronomia",
  "Gestão Ambiental",
  "Gestão Comercial",
  "Gestão Cultural",
  "Gestão de Agronegócios",
  "Gestão de Inventário Extrajudicial",
  "Gestão de Lojas e Pontos de Vendas",
  "Gestão de Micro e Pequenas Empresas",
  "Gestão de Negócios",
  "Gestão de Pessoas",
  "Gestão de Políticas Públicas",
  "Gestão da Avaliação",
  "Gestão de Recursos Humanos",
  "Gestão da Inovação e Empreendedorismo Digital",
  "Gestão da Qualidade",
  "Gestão da Segurança Pública e Patrimonial",
  "Gestão das Organizações do Terceiro Setor",
  "Gestão de Cooperativas",
  "Gestão de Seguros",
  "Gestão de Serviços Judiciários e Notariais",
  "Gestão de Segurança Privada",
  "Gestão de Serviços de Saúde",
  "Gestão Hospitalar",
  "Gestão de Turismo",
  "Gestão de Trânsito",
  "História",
  "Hotelaria",
  "Humanidades",
  "Instrumentação Cirúrgica",
  "Irrigação e Drenagem",
  "Interiores e Decorações",
  "Jornalismo",
  "Laticínios",
  "Letras",
  "Logística",
  "Luteria",
  "Marketing",
  "Matemática",
  "Medicina",
  "Medicina Veterinária",
  "Mediação",
  "Mídias Sociais",
  "Multidisciplinar em Dependência Química",
  "Ministério Pastoral",
  "Negócios Digitais",
  "Negócios Imobiliários",
  "Nutrição",
  "Oftálmica",
  "Odontologia",
  "Óptica e Optometria",
  "Paisagismo",
  "Pedagogia",
  "Psicopedagogia",
  "Psicologia",
  "Produção Agrícola",
  "Produção Agropecuária",
  "Produção Audiovisual",
  "Produção Cervejeira",
  "Produção de Cacau e Chocolate",
  "Produção de Cachaça",
  "Produção de Fármacos",
  "Produção de Grãos",
  "Produção Fonográfica",
  "Produção Leiteira",
  "Produção Musical",
  "Produção Pesqueira",
  "Processos Ambientais",
  "Processos Escolares",
  "Processos Gerenciais",
  "Produção Sucroalcooleira",
  "Propaganda e Marketing",
  "Publicidade e Propaganda",
  "Práticas Integrativas e Complementares",
  "Qualidade de Vida na Contemporaneidade",
  "Radiologia",
  "Rádio, TV e Internet",
  "Relações Internacionais",
  "Relações Públicas",
  "Segurança Alimentar",
  "Segurança da Informação",
  "Segurança no Trabalho",
  "Segurança Pública",
  "Service Design",
  "Sistemas Biomédicos",
  "Silvicultura",
  "Teologia",
  "Terapias Integrativas e Complementares",
  "Terapia Ocupacional",
  "Toxicologia Ambiental",
  "Tradutor e Intérprete",
  "Turismo",
  "Tutoria de Educação a Distância",
  "Varejo Digital",
  "Visagismo e Terapias Capilares",
  "Viticultura e Enologia",
  "Zootecnia",
  "Química",
  "Rochas Ornamentais",
  "Saneamento Ambiental",
  "Segurança da Informação",
  "Ciências Exatas",
  "Ciências Atuariais",
  "Física",
  "Estatística",
  "Oceanografia",
  "Ciência de Dados",
];
