export interface SocioeconomicAnswer {
  question: string;
  answer: string | string[] | number | number[] | boolean;
}
export const stepDescriptions = {
  step1: "Informações Pessoais",
  step2: "Informações de Endereço",
  step3: "Representante Legal",
  step4: "Formulário Sócio-Econômico",
};

export const textoParceria = [
  "O caminho para ingressar em uma universidade pública no Brasil é cheio de desafios, especialmente para estudantes de escolas públicas ou de baixa renda. As universidades públicas, reconhecidas por sua excelência, são um sonho para muitos, mas a preparação necessária para chegar até elas pode parecer distante. É aí que entram os cursinhos populares, aliados importantes na democratização do acesso ao ensino superior.",

  "Os cursinhos populares são iniciativas que oferecem uma preparação acessível e de qualidade para o vestibular e o ENEM. Eles nasceram de movimentos sociais que queriam oferecer uma chance real para todos, independentemente de sua condição financeira, e têm sido uma fonte de apoio para milhares de jovens que desejam entrar na universidade pública.",

  "A parceria entre o Você na Facul (VNF) e os cursinhos populares presenciais busca justamente fortalecer essa trajetória de sucesso. Juntos, estamos oferecendo a você, estudante, uma plataforma que vai além da sala de aula, conectando o conhecimento acadêmico com ferramentas digitais que facilitam o seu progresso.",

  "Com essa parceria, você terá acesso a simulados, materiais de estudo gratuitos e, agora, com as funcionalidades do Você na Facul, você também poderá contar com o acompanhamento do seu cursinho de forma integrada, facilitando o seu processo de inscrição e garantindo que seu progresso seja acompanhado de perto.",

  "Seja bem-vindo! Estamos aqui para ajudar você a alcançar seus sonhos e entrar na universidade pública. Para começar, é só clicar no botão abaixo e fazer a sua inscrição.",
];

export const ptBr = {
  "pt-br": {
    accept: "Sim",
    addRule: "Adicionar Regra",
    am: "AM",
    apply: "Aplicar",
    cancel: "Cancelar",
    choose: "Escolher",
    chooseDate: "Escolher Data",
    chooseMonth: "Escolher Mês",
    chooseYear: "Escolher Ano",
    clear: "Limpar",
    completed: "Concluído",
    contains: "Contém",
    custom: "Personalizado",
    dateAfter: "Data depois de",
    dateBefore: "Data antes de",
    dateFormat: "dd/MM/yy",
    dateIs: "Data é",
    dateIsNot: "Data não é",
    dayNames: [
      "Domingo",
      "Segunda-feira",
      "Terça-feira",
      "Quarta-feira",
      "Quinta-feira",
      "Sexta-feira",
      "Sábado",
    ],
    dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S"],
    dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    emptyFilterMessage: "Nenhum resultado encontrado",
    emptyMessage: "Nenhuma opção disponível",
    emptySearchMessage: "Nenhum resultado encontrado",
    emptySelectionMessage: "Nenhum item selecionado",
    endsWith: "Termina com",
    equals: "Igual",
    fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
    filter: "Filtro",
    firstDayOfWeek: 0,
    gt: "Maior que",
    gte: "Maior ou igual a",
    lt: "Menor que",
    lte: "Menor ou igual a",
    matchAll: "Corresponder Todos",
    matchAny: "Corresponder Qualquer",
    medium: "Médio",
    monthNames: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
      "Setembro",
      "Outubro",
      "Novembro",
      "Dezembro",
    ],
    monthNamesShort: [
      "Jan",
      "Fev",
      "Mar",
      "Abr",
      "Mai",
      "Jun",
      "Jul",
      "Ago",
      "Set",
      "Out",
      "Nov",
      "Dez",
    ],
    nextDecade: "Próxima Década",
    nextHour: "Próxima Hora",
    nextMinute: "Próximo Minuto",
    nextMonth: "Próximo Mês",
    nextSecond: "Próximo Segundo",
    nextYear: "Próximo Ano",
    noFilter: "Sem Filtro",
    notContains: "Não contém",
    notEquals: "Diferente",
    now: "Agora",
    passwordPrompt: "Digite uma senha",
    pending: "Pendente",
    pm: "PM",
    prevDecade: "Década Anterior",
    prevHour: "Hora Anterior",
    prevMinute: "Minuto Anterior",
    prevMonth: "Mês Anterior",
    prevSecond: "Segundo Anterior",
    prevYear: "Ano Anterior",
    reject: "Não",
    removeRule: "Remover Regra",
    searchMessage: "Existem {0} resultados disponíveis",
    selectionMessage: "{0} itens selecionados",
    showMonthAfterYear: false,
    startsWith: "Começa com",
    strong: "Forte",
    today: "Hoje",
    upload: "Enviar",
    weak: "Fraco",
    weekHeader: "Sem",
    aria: {
      cancelEdit: "Cancelar Edição",
      close: "Fechar",
      collapseLabel: "Colapso",
      collapseRow: "Recolher Linha",
      editRow: "Editar Linha",
      expandLabel: "Expandir",
      expandRow: "Expandir Linha",
      falseLabel: "Falso",
      filterConstraint: "Restrição de Filtro",
      filterOperator: "Operador de Filtro",
      firstPageLabel: "Primeira Página",
      gridView: "Visualização de Grade",
      hideFilterMenu: "Esconder Menu de Filtro",
      jumpToPageDropdownLabel: "Ir para a Página",
      jumpToPageInputLabel: "Ir para a Página",
      lastPageLabel: "Última Página",
      listView: "Visualização de Lista",
      moveAllToSource: "Mover Todos para a Origem",
      moveAllToTarget: "Mover Todos para o Destino",
      moveBottom: "Mover para o Final",
      moveDown: "Mover para Baixo",
      moveTop: "Mover para o Topo",
      moveToSource: "Mover para a Origem",
      moveToTarget: "Mover para o Destino",
      moveUp: "Mover para Cima",
      navigation: "Navegação",
      next: "Próximo",
      nextPageLabel: "Próxima Página",
      nullLabel: "Não Selecionado",
      otpLabel: "Insira o caractere da senha de uso único {0}",
      pageLabel: "Página {page}",
      passwordHide: "Esconder a senha",
      passwordShow: "Mostrar senha",
      previous: "Anterior",
      previousPageLabel: "Página Anterior",
      removeLabel: "Remover",
      rotateLeft: "Rotacionar para a Esquerda",
      rotateRight: "Rotacionar para a Direita",
      rowsPerPageLabel: "Linhas por página",
      saveEdit: "Salvar Edição",
      scrollTop: "Rolar para o Topo",
      selectAll: "Todos os itens selecionados",
      selectLabel: "Selecione",
      selectRow: "Linha Selecionada",
      showFilterMenu: "Mostrar Menu de Filtro",
      slide: "Deslizar",
      slideNumber: "Slide {slideNumber}",
      star: "1 estrela",
      stars: "{star} estrelas",
      trueLabel: "Verdadeiro",
      unselectAll: "Todos os itens desmarcados",
      unselectLabel: "Desmarcar",
      unselectRow: "Linha Desmarcada",
      zoomImage: "Ampliar Imagem",
      zoomIn: "Ampliar",
      zoomOut: "Reduzir",
    },
  },
};
