name: vCnafacul

on:
  pull_request: 
    branches: ["develop", "main"]
    types: [opened, synchronize, reopened, closed]

jobs:
  CI:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Iniciando CI
        run: echo "Iniciando CI"
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install depends
        run: yarn
      - name: Build app vCnafacul
        run: yarn build
      - name: Build Image
        run: docker build -t vcnafacul -f web.dockerfile .
      - name: Tag and Push Image
        id: set_tag
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            docker tag vcnafacul vcnafacul/web:latest
            docker push vcnafacul/web:latest
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag vcnafacul vcnafacul/web:stable
            docker push vcnafacul/web:stable
          fi
